# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewTest

  target 'NewTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewTestUITests' do
    # Pods for testing
  end

  pod 'SVProgressHUD'
  pod 'SCLAlertView'
  pod 'NavigationDrawer'
  pod 'DropDown'
  pod 'SideMenu', '~> 6.0'
  pod 'NVActivityIndicatorView'
  pod 'WMSegmentControl'
  pod 'Eureka'
  pod 'FontAwesome.swift'
  pod 'WeScan', '>= 0.9'
  pod 'PhoneNumberKit', '~> 3.1'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SKCountryPicker'
  pod 'ADCountryPicker', '~> 2.1.0'
  pod 'YPDrawSignatureView'
end
