import Foundation

struct Const_Var
{
//    static let BASE_URL = "https://www.origami.life/"
//    static let BASE_URL = "https://migratedev.origami.life/"
    static let BASE_URL = "https://dev.origami.life/"
//    static let BASE_URL = "http://192.168.1.42/"
    
    static let POST_TIME_STAMP       = "api/time.php"
    static let POST_WORK_LEAVE       = "api/insert_request_api.php"
    static let POST_FLOAT            = "api/ios_float.php"
    static let POST_NEED             = "api/insert_need.php"
    static let POST_NEED_ITEM        = "api/insert_new_item_need.php"
    static let POST_NEED_ITEM_IMAGE  = "api/upload_need_image_item.php"
    static let POST_APPROVE          = "api/request_need_api.php"
    static let POST_APPROVE_WORK     = "api/approve_leave_api.php"
    static let POST_APPROVE_FLOAT    = "api/approve_floating.php"
    static let POST_REQUEST_OT       = "api/request_ot.php"
    static let POST_ACCOUNT          = "crm/ios_add_account.php"
    static let POST_ACCOUNT_IMAGE    = "crm/upload_account_image.php"
    static let POST_ACTIVITY         = "crm/ios_add_activity.php"
    static let POST_ACTIVITY_IMAGE   = "crm/ios_upload_activity.php"
    static let POST_ACTIVITY_SKOOP   = "crm/ios_skoop_activity.php"
    static let POST_SKOOP_IMAGE      = "crm/ios_upload_skoop.php"
    static let POST_CLOSE_ACTIVITY   = "crm/ios_close_activity.php"
    static let POST_STAMP_ACTIVITY   = "api/ios_time_stamp.php"
    
    static let UPDATE_NEED           = "api/update_need.php"
    static let UPDATE_NEED_ITEM      = "api/update_item_need.php"
    static let UPDATE_ACCOUNT        = "crm/ios_update_account.php"
    static let UPDATE_ACTIVITY       = "crm/ios_update_activity.php"
    static let UPDATE_WORK           = "api/ios_work_update.php"
    
    static let GET_TIME_STAMP        = "api/get_time_stamp_sim.php"
    static let GET_BRANCH_LIST       = "api/load_branch.php"
    static let GET_ACTIVITY_LIST     = "api/load_time_activity.php"
    static let GET_UNDER_USER_LIST   = "api/get_under_user.php"
    static let GET_WORK_BALANCE      = "api/ios_work_balance.php"
    static let GET_WORK_BALANCES     = "api/get_work.php"
    static let GET_WORK_LEAVE        = "api/get_list_work.php"
    static let GET_NEED_LIST         = "api/load_list_request_need.php"
    static let GET_NEED_ITEMS        = "api/load_list_pageneed_1.php"
    static let GET_NEED_DETAILS      = "api/load_need_item.php"
    static let GET_NEED_ITEM_DETAIL  = "api/loadDetailNeed.php"
    static let GET_NEED_APPROVE      = "api/load_approve_detail.php"
    static let GET_WORK_REQUEST      = "api/get_request_prove.php"
    static let GET_NEED_REQUEST      = "api/load_list_need.php"
    static let GET_REQUEST_OT        = "api/request_ot_list.php"
    static let GET_WORK_SHIFT        = "api/ios_leave_shift.php"
    static let GET_FLOAT_SHIFT       = "api/ios_float_shift.php"
    static let GET_ACCOUNT_LIST      = "crm/ios_account.php"
    static let GET_ACCOUNT_GROUP     = "crm/select_account_group.php"
    static let GET_ACCOUNT_STATUS    = "crm/select_account_status.php"
    static let GET_ACCOUNT_TYPE      = "crm/select_account_type.php"
    static let GET_ADDRESS_COMPN     = "crm/get_address_component.php"
    static let GET_PAYMENT           = "crm/get_payment.php"
    static let GET_ACCOUNT_CONTACT   = "crm/get_account_contact.php"
    static let GET_ACCOUNT_PROJECT   = "crm/get_account_project.php"
    static let GET_ACCOUNT_ACTIVITY  = "crm/get_account_activity.php"
    static let GET_START_END_WORK    = "crm/get_start_end_work.php"
    static let GET_NUMBER_TYPE       = "crm/get_number_type.php"
    static let GET_ADDRESS_TXT       = "crm/get_addresss_text.php"
    static let GET_ACTIVITY          = "crm/ios_activity.php"
    static let GET_ACTIVITY_TYPE     = "crm/ios_activity_type.php"
    static let GET_ACTIVITY_PROJECT  = "crm/ios_activity_project.php"
    static let GET_ACTIVITY_STATUS   = "crm/ios_activity_status.php"
    static let GET_ACTIVITY_PRIORITY = "crm/ios_activity_priority.php"
    static let GET_ACTIVITY_CONTACT  = "crm/ios_activity_contact.php"
    static let GET_ACTIVITY_INFO     = "crm/ios_activity_info.php"
    static let GET_ACTIVITY_FILE     = "crm/ios_activity_file.php"
    static let GET_SKOOP_IMAGE       = "crm/ios_skoop_file.php"
    static let GET_MENU              = "crm/check_permission_menu.php"
    static let GET_WORK_EDIT         = "api/ios_work_edit.php"
    
    static let DEL_WORK              = "api/ios_work_delete.php"
    static let DEL_NEED              = "api/action_del_data.php"
    static let DEL_REQUEST_OT        = "api/delete_request_ot.php"
    static let DEL_ITEM_IMAGE        = "api/delete_item_image.php"
    static let DEL_ACCOUNT           = "crm/ios_delete_account.php"
    static let DEL_ACTIVITY          = "crm/ios_delete_activity.php"
    static let DEL_ACTIVITY_IMAGE    = "crm/ios_delete_activity_image.php"
    static let DEL_SKOOP_IMAGE       = "crm/ios_delete_skoop_image.php"
}
